### ISSUE TITLE
Lock Task ambiguous

### ISSUE THREAD

**Issue by zN3utr4l** [avryhof/huey_django_orm#1]
I opened this issue on huey, but I'm not sure if the error depends on them or on huey_django_orm.
Could you take a look at the issue?

https://github.com/coleifer/huey/issues/763

**Comment by avryhof** [comment]
I haven't done anything with lock tasks.  I mostly just use huey to enqueue long-running processes like using transformers to generate images, or updating user records from slow API calls in the background.

Also, I don't actually use Huey with the ORM anymore, and have moved all of my projects to redis.

I've got a few busy days coming up, and may yet loop back to this, but it won't be right away.

My recommendation is to pinpoint the actual issue. I'd say to give it a shot with SqliteHuey, since it's officially supported, and also the basis for this code.

Reading through [https://github.com/coleifer/huey/issues/764](https://github.com/coleifer/huey/issues/764) it looks like you are having some other DB issues.  

Are you using something to manage connection pools that might be closing the connection without the ORM knowing?

**Comment by zN3utr4l** [comment]
I use PGBouncer with Postgres.
I wanted to find a solution for Windows that doesn't need other services to schedule and execute tasks.

I'll try to use SqliteHuey, also because they tell me it doesn't depend on them:
https://github.com/coleifer/huey/issues/763#issuecomment-1710036442

**Comment by VBobCat** [comment]
I sent a [pull request](https://github.com/avryhof/huey_django_orm/pull/4) that seems to help with this issue.

**Comment by VBobCat** [comment]
@zN3utr4l, if this is still an issue for you, would you try installing [huey-django-orm==23.12.10.0](https://pypi.org/project/huey-django-orm/23.12.10.0/) and see if it solved the problem? Thanks!

**Comment by VBobCat** [comment]
@avryhof perhaps this issue could be closed. For me, at least, no further problems happened after the patch.

**Comment by avryhof** [comment]
Sure thing.  

@VBobCat  I've invited you to the repo.  If you accept the invite, I can give you access to merge PRs and manage issues.

I keep moving up the ladder in organizations I work with, so I have very little time for side projects.  I'll still pop in and contribute when I can, but day-to-day management isn't really possible.

**Comment by VBobCat** [comment]
@avryhof, I'm honored. To be honest, I'm short of time as well, but since this project is important for the application I develop and maintain, I'll try to check other issues in future as well.

**Comment by avryhof** [comment]
@VBobCat - Thank you.  I appreciate the help.  I'll continue to monitor and address issues as I'm able, but as I don't actually use this in anything these days, the additional diligence and attention certainly helps.
